In [1]:
import numpy as np

In [2]:
a = np.arange(21)

In [3]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [4]:
b = a.reshape(3, 7)

In [5]:
b

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20]])

In [6]:
a.shape

(21,)

In [7]:
b.shape

(3, 7)

In [8]:
a.ndim

1

In [9]:
b.ndim

2

In [10]:
a.dtype.name

'int32'

In [11]:
type(a)

numpy.ndarray

In [15]:
c = np.array([[1., 2., 3.],
              [4., 5.5, 6.]])

In [16]:
c

array([[1. , 2. , 3. ],
       [4. , 5.5, 6. ]])

In [17]:
c.dtype

dtype('float64')

In [19]:
d= np.array([(1,2,3),(4,5.5,6)], dtype=int)

In [20]:
d

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
np.full((3,3), 777.7)

array([[777.7, 777.7, 777.7],
       [777.7, 777.7, 777.7],
       [777.7, 777.7, 777.7]])

In [24]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [26]:
np.arange(1,20,1.9)

array([ 1. ,  2.9,  4.8,  6.7,  8.6, 10.5, 12.4, 14.3, 16.2, 18.1])

In [27]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [28]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [29]:
e = np.array([1,2,3,4])

In [30]:
f = np.arange(4)

In [31]:
f

array([0, 1, 2, 3])

In [32]:
e*f

array([ 0,  2,  6, 12])

In [33]:
e-f

array([1, 1, 1, 1])

In [34]:
e*3

array([ 3,  6,  9, 12])

In [35]:
e**3

array([ 1,  8, 27, 64], dtype=int32)

In [39]:
g= np.arange(9).reshape(3,3)

In [37]:
g

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [40]:
h=np.arange(9).reshape(3,3) + 1

In [41]:
h

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
g**2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]], dtype=int32)

In [43]:
g**h

array([[        0,         1,         8],
       [       81,      1024,     15625],
       [   279936,   5764801, 134217728]], dtype=int32)

In [44]:
g.dot(h)

array([[ 18,  21,  24],
       [ 54,  66,  78],
       [ 90, 111, 132]])

In [45]:
np.dot(g,h)

array([[ 18,  21,  24],
       [ 54,  66,  78],
       [ 90, 111, 132]])

In [46]:
g>3

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [48]:
i = np.array([[[[1,2],[3,4]]]], dtype=np.float64)
i

array([[[[1., 2.],
         [3., 4.]]]])

In [49]:
i.dtype

dtype('float64')

In [50]:
i.ndim

4

In [51]:
j=np.random.random((5,2))

In [52]:
j

array([[0.75108968, 0.79912515],
       [0.73326532, 0.19086744],
       [0.40259774, 0.82139191],
       [0.61987474, 0.5365579 ],
       [0.72849023, 0.7124705 ]])

In [53]:
j.min()

0.19086743861463318

In [55]:
j.sum(axis=0)

array([3.23531771, 3.0604129 ])